package main

type Organization struct {
	ID                  int    `json:"id"`
	Name                string `json:"name"`
	ShortName           string `json:"short_name"`
	UnitTypeName        string `json:"unit_type_name"`
	Kind                any    `json:"kind"`
	Ogrn                any    `json:"ogrn"`
	OgrnDate            any    `json:"ogrn_date"`
	Inn                 string `json:"inn"`
	Kpp                 string `json:"kpp"`
	Oktmo               any    `json:"oktmo"`
	Okpo                any    `json:"okpo"`
	Okato               string `json:"okato"`
	Okopf               any    `json:"okopf"`
	Okfs                any    `json:"okfs"`
	Okogu               any    `json:"okogu"`
	Director            any    `json:"director"`
	Telephone           any    `json:"telephone"`
	Fax                 any    `json:"fax"`
	Email               any    `json:"email"`
	WebSite             any    `json:"web_site"`
	FAddress            any    `json:"f_address"`
	FAddressStreet      any    `json:"f_address_street"`
	FAddressHouse       any    `json:"f_address_house"`
	FAddressFlat        any    `json:"f_address_flat"`
	FAddressHouseGUID   any    `json:"f_address_house_guid"`
	FZipcode            any    `json:"f_zipcode"`
	FAddressFull        any    `json:"f_address_full"`
	UAddress            any    `json:"u_address"`
	UAddressStreet      any    `json:"u_address_street"`
	UAddressHouse       any    `json:"u_address_house"`
	UAddressFlat        any    `json:"u_address_flat"`
	UZipcode            any    `json:"u_zipcode"`
	UAddressFull        any    `json:"u_address_full"`
	UAddressHouseGUID   any    `json:"u_address_house_guid"`
	EntranceAddressFull any    `json:"entrance_address_full"`
	DaysForScoreEditing any    `json:"days_for_score_editing"`
	ViewInPortal        bool   `json:"view_in_portal"`
	HostelOffering      bool   `json:"hostel_offering"`
	ShowBranchData      bool   `json:"show_branch_data"`
	RosobrID            any    `json:"rosobr_id"`
	StudyFormID         int    `json:"study_form_id"`
	StudyFormName       string `json:"study_form_name"`
	TerritoryID         any    `json:"territory_id"`
	TerritoryName       any    `json:"territory_name"`
	TerritoryCode       any    `json:"territory_code"`
	TerritoryOkato      any    `json:"territory_okato"`
	TerritoryTypeID     int    `json:"territory_type_id"`
	TerritoryTypeName   string `json:"territory_type_name"`
	VariantID           int    `json:"variant_id"`
	VariantName         string `json:"variant_name"`
	VariantTypeID       string `json:"variant_type_id"`
	VariantTypeName     string `json:"variant_type_name"`
	BankDetails         []any  `json:"bank_details"`
	Accreditations      []any  `json:"accreditations"`
	Founders            []any  `json:"founders"`
	Licenses            []any  `json:"licenses"`
	Normdocs            []any  `json:"normdocs"`
	StudyPlans          []any  `json:"study_plans"`
	WorkPrograms        []any  `json:"work_programs"`
	YearGraphs          []any  `json:"year_graphs"`
	Language            any    `json:"language"`
	Timezone            string `json:"timezone"`
	Parent              any    `json:"parent"`
	Close               bool   `json:"close"`
	Ignore              bool   `json:"ignore"`
	Created             string `json:"created"`
	Modified            string `json:"modified"`
	TreeData            struct {
		Left   int `json:"left"`
		Right  int `json:"right"`
		TreeID int `json:"tree_id"`
	} `json:"tree_data"`
}
